version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false #desativar segurança
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 700m

  kibana:
    image: kibana:7.17.7
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - NODE_OPTIONS=--max-old-space-size=512
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 700m

  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_payment
      - MYSQL_USER=randomuser
      - MYSQL_PASSWORD=randompassword
      - MYSQL_ROOT_PASSWORD=randomrootpassword
    container_name: mysql
    restart: always
    ports:
      - 33060:3306
    # volumes:
    #   - ./.docker/mysql:/docker-entrypoint-initdb.d
    tmpfs: # aquivos inteiros na memoria ram para melhorar velocidade de leitura
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
  # app:
  #   build: .
  #   container_name: node
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
